name = "openai-api-worker"
main = "src/index.ts"
compatibility_date = "2025-02-11"
compatibility_flags = ["nodejs_compat"]

# Enable observability and logging
[observability]
enabled = true
head_sampling_rate = 1

[ai]
binding = "AI"

[assets]
directory = "./static"
binding = "ASSETS"

# KV storage for AI memory
[[kv_namespaces]]
binding = "AI_MEMORY"
id = "b4f97532377e45e99fd5c7e3d7f1037d"
preview_id = "a4dd3af7da29476f9ed717d29e87dc1c"

# Service binding to core API worker
[[services]]
binding = "CORE_API"
service = "core-api"

[vars]
# Default models configuration
DEFAULT_MODEL = "@cf/meta/llama-4-scout-17b-16e-instruct"
BACKUP_MODEL = "@cf/openai/gpt-oss-120b"

# Environment-specific variables (set these using wrangler secret put)
# WORKER_API_KEY = "your-secure-worker-api-key"
# OPENAI_API_KEY = "sk-your-openai-api-key"  
# GEMINI_API_KEY = "your-gemini-api-key"
# CORE_WORKER_API_KEY = "your-core-worker-api-key"

# Debug mode (set to "true" in development)
# DEBUG_LOGGING = "false"
