name = "openai-api-worker"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Enable observability and logging
observability = { enabled = true }
logpush = true

[ai]
binding = "AI"

[assets]
directory = "./static"
binding = "ASSETS"

# Service binding to core API worker
[[services]]
binding = "CORE_API"
service = "core-api"
environment = "production"

[vars]
# Default models configuration
DEFAULT_MODEL = "@cf/meta/llama-4-scout-17b-16e-instruct"
BACKUP_MODEL = "@cf/openai/gpt-oss-120b"
# Core API configuration
CORE_WORKER_API_KEY = "your-core-api-key-here"
# Enable debug logging
DEBUG_LOGGING = "true"

# Environment-specific variables
[env.production.vars]
# Set these in production via wrangler secret put
# WORKER_API_KEY will be set as a secret
DEBUG_LOGGING = "false"

[env.development.vars]
# Development variables loaded from .dev.vars
DEBUG_LOGGING = "true"
